oslabs-beta/spearmint_LA42

.gitignore, src/components/Terminal/Terminal.jsx
Ready for linking to tabbed view.
=> Added terminal component

package.json, src/components/Terminal/TerminalGenerator.jsx, src/components/Terminal/TerminalView.module.scss, src/pages/RightPanel/RightPanel.jsx
Terminal formatting has been finalized as well as the font size. We ran Jest commands to confirm testing functionality works. We are ready for custom commands to be sent to the terminal.
=> Terminal Formatting

src/components/NavBar/NavBar.jsx, src/pages/RightPanel/RightPanel.jsx
Co-authored-by: Dieu Huynh <dieuhhuynh@gmail.com>
=> Removed home button that creates redundant ptyProcess.

src/components/Modals/ExportFileModal.module.scss, src/components/Modals/Modal.jsx, src/pages/TestFile/TestFile.jsx
- Testing Modal overlay no longer obfuscates Right Panel
- Dynamic positioning for testing modal when file directory is opened and closed
- Added escape buttons to modals.
=> Testing modal Updates

src/components/Modals/ExportFileModal.module.scss, src/components/Modals/Modal.jsx, src/components/TestMenu/AccTestMenu.tsx, src/components/TestMenu/EndpointTestMenu.tsx, src/components/TestMenu/HooksTestMenu.tsx, src/components/TestMenu/PuppeteerTestMenu.tsx, src/components/TestMenu/ReactTestMenu.jsx, src/components/TestMenu/ReduxTestMenu.tsx, src/components/TestMenu/testMenuHooks.js, src/context/actions/globalActions.js, src/context/reducers/globalReducer.js, src/pages/RightPanel/RightPanel.jsx
Added auto navigation functionality.
- Moved the tab index into global context
- Added action types, reducer function and incorporated a dispatch function into the file handling function in each testing file.
=> Auto navigating to specific tab when clicking "preview" or "run" button 

public/electron.js, src/components/Modals/Modal.jsx, src/components/OpenFolder/OpenFolderButton.jsx
Fixed line break issues when looking at jest commands in modal.
=> Line Break Issues

src/components/BrowserView/BrowserView.jsx, src/components/Modals/Modal.jsx, src/components/NavBar/NavBar.jsx, src/context/reducers/globalReducer.js, src/pages/RightPanel/RightPanel.jsx
- Updated modal overlay and positioning to prevent blocking of file directory. 
- Eliminated redundant "codeview" and "close right panel" buttons.
=> Updated Modal Overlay and removed redundant buttons

src/context/useGenerateTest.jsx
Co-authored-by: Dieu Huynh <dieuhhuynh@gmail.com>
=> Added import react statement to react testing

src/context/useGenerateTest.jsx
Co-authored-by: Dieu Huynh <dieuhhuynh@gmail.com>:
=> Updated useGenerateTest file to use dot notation.

src/components/Modals/Modal.jsx, src/components/TestMenu/AccTestMenu.tsx, src/components/TestMenu/EndpointTestMenu.tsx, src/components/TestMenu/HooksTestMenu.tsx, src/components/TestMenu/PuppeteerTestMenu.tsx, src/components/TestMenu/ReactTestMenu.jsx, src/components/TestMenu/ReduxTestMenu.tsx
Co-authored-by: Dieu Huynh <dieuhhuynh@gmail.com>
=> Added warning screen when changing tests without saving

src/components/Modals/ExportFileModal.module.scss, src/components/Modals/Modal.jsx, src/components/Modals/modalHooks.js
1. Linked Puppeteer testing command to terminal 
2. Added Endpoint-config guide to the modal
3. Added styling for Endpoint-config guide
=> Linked Puppeteer testing command to terminal & Added Endpoint-config Guide to the modal

public/electron.js, src/components/Terminal/TerminalView.tsx, src/context/reducers/accTestCaseReducer.ts, src/pages/RightPanel/RightPanel.jsx, src/utils/ptyTypes.ts, src/utils/terminalTypes.ts, tsconfig.json
- Converted TerminalView.jsx to .tsx
- Added types for values in TerminalView.tsx
=> TypeScript Additions

src/components/EditorView/EditorView.jsx, src/components/Modals/ExportFileModal.module.scss, src/components/Modals/Modal.jsx
- Fixed issue for Window's user's cursors not aligning correctly while in the Monaco Editor.
- Added a React Babel Configuration section to Modal when in Hooks testing suite and React testing suite.
=> Monaco Editor Fix and Modal Updates

package.json, src/components/Modals/modalHooks.js, src/context/useGenerateTest.jsx
- Fixed code generated by Endpoint testing suite
- Added missing regenerator-runtime dependency to Endpoint testing
- Updated version number for spearmint in package.json
=> Fixed Endpoint Testing

package.json, public/electron.js
- Added configuration for Linux build command
- Made install-once command work for both Mac and Windows users
=> Linux Build Command and Install-Once

src/components/BrowserView/BrowserView.jsx, src/components/BrowserView/BrowserView.module.scss
Co-authored-by: Dieu Huynh <dieuhhuynh@gmail.com>
=> Improved stylization of Accessibility Lens. 

package.json
- Fixed acc lens formatting
- Removed trailing comma from package.json that was throwing an error
=> Acc Lens Formatting

package.json
- Changed install-once script to use && instead of concurrently
=> Updated install-once script

package.json, src/components/BrowserView/BrowserView.module.scss
- Made acc lens box a static value so it will not shrink when vertically resizing the app window
=> Acc Lens CSS Changes

README.md
- Changed from .jpg to .png
- Punctuation fixes
- Removed duplicates
=> Proof read README
